apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
rules:
# Allow for performing leader election.
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - update
# Allow for emitting events.
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
# Allow for creating, reading, listing, updating and watching CustomResourceDefinition resources.
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - update
  - watch
# Allow for reading, creating and updating MutatingWebhookConfiguration resources.
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - update
# Allow for creating and reading secrets.
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
# Allow for reading PostgresqlInstance resources.
- apiGroups:
  - cloudsql.travelaudience.com
  resources:
  - postgresqlinstances
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudsql-postgres-operator
subjects:
  - kind: ServiceAccount
    name: cloudsql-postgres-operator
    namespace: cloudsql-postgres-operator
