apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
data:
  config.toml: |
    [logging]
    level = "trace"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
spec:
  selector:
    app: cloudsql-postgres-operator
  ports:
  - name: admission
    port: 443
    targetPort: 443
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cloudsql-postgres-operator
  name: cloudsql-postgres-operator
  namespace: cloudsql-postgres-operator
spec:
  containers:
  - name: cloudsql-postgres-operator
    image: "gcr.io/<project-id>/cloudsql-postgres-operator"
    imagePullPolicy: IfNotPresent
    args:
    - /cloudsql-postgres-operator
    - --config-file
    - /cfg/config.toml
    ports:
    - name: admission
      containerPort: 443
    readinessProbe:
      httpGet:
        path: /healthz
        port: admission
        scheme: HTTPS
    volumeMounts:
    - mountPath: /cfg/config.toml
      subPath: config.toml
      name: cfg
      readOnly: true
  volumes:
  - name: cfg
    configMap:
      name: cloudsql-postgres-operator
  serviceAccountName: cloudsql-postgres-operator
